services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: musiccloud-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Patata123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ../data/sqlserver:/var/opt/mssql
    restart: unless-stopped
